version: "3"

networks:
  juice-shop-net:
    driver: bridge

services:
  juice-shop:
    container_name: juice-shop
    restart: always
    networks:
      - juice-shop-net
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
